import { useEffect, useState } from 'react'
import { addBankQuestionToQuiz, createBankQuestion, downloadQuestionTemplate, getQuestionCategories, importQuestionFile, searchBankQuestions } from '@/services/questionBankService'
import { getMyQuizzes } from '@/services/quizService'

export default function QuestionBank() {
  const [items,setItems]=useState<any[]>([]), [categories,setCategories]=useState<any[]>([]), [quizzes,setQuizzes]=useState<any[]>([])
  const [search,setSearch]=useState(''), [message,setMessage]=useState(''), [targetQuiz,setTargetQuiz]=useState(0), [showNew,setShowNew]=useState(false)
  const [draft,setDraft]=useState({texte:'',type:'CHOIX_UNIQUE',answers:['','','',''],correct:0})
  const load=()=>searchBankQuestions({search}).then(setItems).catch(()=>setItems([]))
  useEffect(()=>{ load(); getQuestionCategories().then(setCategories).catch(()=>{}); getMyQuizzes().then(setQuizzes).catch(()=>{}) },[])
  const create=async()=>{ await createBankQuestion({texte:draft.texte,type:draft.type,difficulte:'MOYEN',dureeSecondes:30,points:100,reponses:draft.answers.filter(Boolean).map((texte,i)=>({texte,correcte:i===draft.correct,option:String.fromCharCode(65+i)}))}); setShowNew(false); setDraft({texte:'',type:'CHOIX_UNIQUE',answers:['','','',''],correct:0}); setMessage('Question saved'); load() }
  return <div style={{padding:28}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 style={{marginBottom:4}}>Question bank</h1><p style={{color:'#64748B'}}>Reuse, filter, create, and import your questions.</p></div><div style={{display:'flex',gap:8}}><button onClick={()=>setShowNew(!showNew)}>+ New question</button><button onClick={downloadQuestionTemplate}>Template</button><label style={{padding:'9px 14px',background:'#2563EB',color:'#fff',borderRadius:8,cursor:'pointer'}}>Import Excel<input type="file" accept=".xlsx,.xls" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const r=await importQuestionFile(f);setMessage(`Imported ${r.imported}; rejected ${r.rejected}`);load()}} /></label></div></div>
    {message&&<p style={{color:'#16A34A'}}>{message}</p>}
    {showNew&&<div style={{background:'#fff',padding:16,border:'1px solid #E2E8F0',borderRadius:12,display:'grid',gap:8}}><input placeholder="Question text" value={draft.texte} onChange={e=>setDraft({...draft,texte:e.target.value})}/>{draft.answers.map((answer,i)=><div key={i} style={{display:'flex',gap:8}}><input type="radio" checked={draft.correct===i} onChange={()=>setDraft({...draft,correct:i})}/><input placeholder={`Answer ${String.fromCharCode(65+i)}`} value={answer} onChange={e=>{const a=[...draft.answers];a[i]=e.target.value;setDraft({...draft,answers:a})}}/></div>)}<button disabled={!draft.texte||draft.answers.filter(Boolean).length<2} onClick={create}>Save to bank</button></div>}
    <div style={{display:'flex',gap:8,margin:'20px 0',flexWrap:'wrap'}}><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search question text…" style={{flex:1,minWidth:220,padding:10,border:'1px solid #CBD5E1',borderRadius:8}}/><select onChange={e=>searchBankQuestions({search,categoryId:e.target.value?Number(e.target.value):undefined}).then(setItems)}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select><select value={targetQuiz} onChange={e=>setTargetQuiz(Number(e.target.value))}><option value={0}>Choose target quiz</option>{quizzes.map(q=><option key={q.id} value={q.id}>{q.titre}</option>)}</select><button onClick={load}>Search</button></div>
    <div style={{display:'grid',gap:12}}>{items.map(q=><article key={q.id} style={{background:'#fff',border:'1px solid #E2E8F0',borderRadius:12,padding:16}}><div style={{color:'#64748B',fontSize:12}}>{q.categorieNom||'Uncategorized'} · {q.type} · {q.difficulte}</div><h3>{q.texte}</h3><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{q.reponses?.map((a:any)=><span key={a.id} style={{padding:'5px 8px',background:a.correcte?'#DCFCE7':'#F1F5F9',borderRadius:6,fontSize:12}}>{a.option}. {a.texte}</span>)}</div><button disabled={!targetQuiz} onClick={async()=>{await addBankQuestionToQuiz(q.id,targetQuiz);setMessage('Question copied into quiz')}} style={{marginTop:12}}>Add to selected quiz</button></article>)}</div>
  </div>
}
