package com.quizapp.service;

import com.quizapp.dto.*;
import com.quizapp.exception.*;
import com.quizapp.model.*;
import com.quizapp.model.enums.*;
import com.quizapp.repository.*;
import lombok.RequiredArgsConstructor;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import java.io.ByteArrayOutputStream;
import java.util.*;

@Service @RequiredArgsConstructor
public class QuestionBankService {
    private final BankQuestionRepository bankRepository; private final QuestionCategoryRepository categoryRepository;
    private final MatiereRepository matiereRepository; private final QCMRepository qcmRepository; private final QuestionRepository questionRepository;
    private final UtilisateurRepository utilisateurRepository;

    @Transactional(readOnly=true) public List<QuestionCategoryDTO> categories(){ return categoryRepository.findByEnseignantIdOrderByNomAsc(currentTeacher().getId()).stream().map(c->QuestionCategoryDTO.builder().id(c.getId()).nom(c.getNom()).build()).toList(); }
    @Transactional public QuestionCategoryDTO createCategory(String name){ Enseignant t=currentTeacher(); if(name==null||name.isBlank()) throw new BusinessException("Category name is required"); QuestionCategory c=categoryRepository.findByEnseignantIdAndNomIgnoreCase(t.getId(),name.trim()).orElseGet(()->categoryRepository.save(QuestionCategory.builder().nom(name.trim()).enseignant(t).build())); return QuestionCategoryDTO.builder().id(c.getId()).nom(c.getNom()).build(); }
    @Transactional(readOnly=true) public List<BankQuestionDTO> search(String search,Long subjectId,Long categoryId){ String term=search==null||search.isBlank()?null:search.trim(); return bankRepository.search(currentTeacher().getId(),term,subjectId,categoryId).stream().map(this::dto).toList(); }
    @Transactional public BankQuestionDTO create(BankQuestionRequest r){ validate(r); Enseignant t=currentTeacher(); BankQuestion q=new BankQuestion(); apply(q,r,t); return dto(bankRepository.save(q)); }
    @Transactional public BankQuestionDTO update(Long id,BankQuestionRequest r){ validate(r); BankQuestion q=owned(id); apply(q,r,currentTeacher()); return dto(bankRepository.save(q)); }
    @Transactional public void delete(Long id){ bankRepository.delete(owned(id)); }
    @Transactional public QuestionDTO addToQuiz(Long bankId,Long quizId){ BankQuestion b=owned(bankId); QCM quiz=ownedQuiz(quizId); Question q=Question.builder().texte(b.getTexte()).type(b.getType()).ordre(quiz.getQuestions().size()+1).dureeSecondes(b.getDureeSecondes()).points(b.getPoints()).explication(b.getExplication()).mediaUrl(b.getMediaUrl()).mediaType(b.getMediaType()).mediaAlt(b.getMediaAlt()).qcm(quiz).build(); for(BankAnswer a:b.getReponses()) q.getReponses().add(Reponse.builder().texte(a.getTexte()).correcte(a.getCorrecte()).option(a.getOption()).question(q).build()); q=questionRepository.save(q); return QuestionDTO.builder().id(q.getId()).texte(q.getTexte()).type(q.getType()).ordre(q.getOrdre()).dureeSecondes(q.getDureeSecondes()).points(q.getPoints()).explication(q.getExplication()).mediaUrl(q.getMediaUrl()).mediaType(q.getMediaType()).mediaAlt(q.getMediaAlt()).reponses(q.getReponses().stream().map(a->ReponseDTO.builder().id(a.getId()).texte(a.getTexte()).correcte(a.getCorrecte()).option(a.getOption()).build()).toList()).build(); }

    @Transactional public QuestionImportResultDTO importExcel(MultipartFile file){ if(file==null||file.isEmpty()) throw new BusinessException("Select an Excel file"); int imported=0,rejected=0; List<String> errors=new ArrayList<>(); try(Workbook wb=WorkbookFactory.create(file.getInputStream())){ Sheet s=wb.getSheetAt(0); for(int i=1;i<=s.getLastRowNum();i++){ Row row=s.getRow(i); if(row==null||text(row,4).isBlank()) continue; try{ BankQuestionRequest r=fromRow(row); create(r); imported++; }catch(Exception ex){ rejected++; errors.add("Row "+(i+1)+": "+ex.getMessage()); } } }catch(Exception ex){ throw new BusinessException("Invalid Excel file: "+ex.getMessage()); } return QuestionImportResultDTO.builder().imported(imported).rejected(rejected).errors(errors).build(); }
    public byte[] template(){ try(Workbook wb=new XSSFWorkbook(); ByteArrayOutputStream out=new ByteArrayOutputStream()){ Sheet s=wb.createSheet("Questions"); Row h=s.createRow(0); String[] headers={"Category","Subject code","Difficulty","Type","Question","Answer A","Answer B","Answer C","Answer D","Correct letters","Explanation","Seconds","Points","Media URL"}; for(int i=0;i<headers.length;i++) h.createCell(i).setCellValue(headers[i]); Row sample=s.createRow(1); String[] values={"Programming","INFO","FACILE","CHOIX_UNIQUE","Which logo is Python?","Python","Java","C++","Ruby","A","Python uses the two-snake logo.","30","100","https://example.com/python.png"}; for(int i=0;i<values.length;i++) sample.createCell(i).setCellValue(values[i]); for(int i=0;i<headers.length;i++) s.autoSizeColumn(i); wb.write(out); return out.toByteArray(); }catch(Exception ex){ throw new BusinessException("Unable to generate template"); } }

    private BankQuestionRequest fromRow(Row row){ BankQuestionRequest r=new BankQuestionRequest(); String category=text(row,0), subjectCode=text(row,1); r.setDifficulte(parse(DifficulteEnum.class,text(row,2),DifficulteEnum.MOYEN)); r.setType(parse(TypeQuestionEnum.class,text(row,3),TypeQuestionEnum.CHOIX_UNIQUE)); r.setTexte(text(row,4)); r.setExplication(text(row,10)); r.setDureeSecondes(number(row,11,30)); r.setPoints(number(row,12,100)); r.setMediaUrl(text(row,13)); if(!r.getMediaUrl().isBlank()) r.setMediaType(r.getMediaUrl().matches("(?i).*(mp4|webm)(\\?.*)?$")?"VIDEO":"IMAGE"); Enseignant t=currentTeacher(); if(!category.isBlank()) r.setCategorieId(createCategory(category).getId()); if(!subjectCode.isBlank()){ Matiere m=matiereRepository.findByCode(subjectCode).orElseThrow(()->new ResourceNotFoundException("Unknown subject code "+subjectCode)); if(!t.getMatieres().contains(m)) throw new ForbiddenException("Subject "+subjectCode+" is not assigned to you"); r.setMatiereId(m.getId()); } Set<String> correct=new HashSet<>(Arrays.asList(text(row,9).toUpperCase().split("\\s*,\\s*"))); List<CreateReponseRequest> answers=new ArrayList<>(); for(int i=0;i<4;i++){ String value=text(row,5+i); if(value.isBlank()) continue; CreateReponseRequest a=new CreateReponseRequest(); a.setTexte(value); a.setOption(String.valueOf((char)('A'+i))); a.setCorrecte(correct.contains(a.getOption())); answers.add(a); } r.setReponses(answers); return r; }
    private void apply(BankQuestion q,BankQuestionRequest r,Enseignant t){ q.setTexte(r.getTexte().trim()); q.setType(r.getType()); q.setDifficulte(r.getDifficulte()==null?DifficulteEnum.MOYEN:r.getDifficulte()); q.setDureeSecondes(r.getDureeSecondes()); q.setPoints(r.getPoints()); q.setExplication(r.getExplication()); q.setMediaUrl(blank(r.getMediaUrl())); q.setMediaType(blank(r.getMediaType())); q.setMediaAlt(blank(r.getMediaAlt())); q.setEnseignant(t); q.setMatiere(r.getMatiereId()==null?null:assignedSubject(t,r.getMatiereId())); q.setCategorie(r.getCategorieId()==null?null:ownedCategory(t,r.getCategorieId())); if(q.getReponses()==null) q.setReponses(new ArrayList<>()); q.getReponses().clear(); int i=0; for(CreateReponseRequest a:r.getReponses()){ q.getReponses().add(BankAnswer.builder().texte(a.getTexte().trim()).correcte(Boolean.TRUE.equals(a.getCorrecte())).option(a.getOption()==null?String.valueOf((char)('A'+i)):a.getOption()).question(q).build()); i++; } }
    private void validate(BankQuestionRequest r){ if(r.getType()!=TypeQuestionEnum.TEXTE_LIBRE){ if(r.getReponses()==null||r.getReponses().size()<2) throw new BusinessException("At least two answers are required"); long c=r.getReponses().stream().filter(a->Boolean.TRUE.equals(a.getCorrecte())).count(); if(c==0) throw new BusinessException("Select a correct answer"); if((r.getType()==TypeQuestionEnum.CHOIX_UNIQUE||r.getType()==TypeQuestionEnum.VRAI_FAUX)&&c!=1) throw new BusinessException("Exactly one correct answer is required"); } }
    private BankQuestion owned(Long id){ BankQuestion q=bankRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Bank question not found")); if(!q.getEnseignant().getId().equals(currentTeacher().getId())) throw new ForbiddenException("Question does not belong to you"); return q; }
    private QCM ownedQuiz(Long id){ QCM q=qcmRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Quiz not found")); if(!q.getEnseignant().getId().equals(currentTeacher().getId())) throw new ForbiddenException("Quiz does not belong to you"); return q; }
    private QuestionCategory ownedCategory(Enseignant t,Long id){ QuestionCategory c=categoryRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Category not found")); if(!c.getEnseignant().getId().equals(t.getId())) throw new ForbiddenException("Category does not belong to you"); return c; }
    private Matiere assignedSubject(Enseignant t,Long id){ Matiere m=matiereRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Subject not found")); if(!t.getMatieres().contains(m)) throw new ForbiddenException("Subject is not assigned to you"); return m; }
    private BankQuestionDTO dto(BankQuestion q){ return BankQuestionDTO.builder().id(q.getId()).texte(q.getTexte()).type(q.getType()).difficulte(q.getDifficulte()).dureeSecondes(q.getDureeSecondes()).points(q.getPoints()).explication(q.getExplication()).mediaUrl(q.getMediaUrl()).mediaType(q.getMediaType()).mediaAlt(q.getMediaAlt()).matiereId(q.getMatiere()==null?null:q.getMatiere().getId()).matiereNom(q.getMatiere()==null?null:q.getMatiere().getNom()).categorieId(q.getCategorie()==null?null:q.getCategorie().getId()).categorieNom(q.getCategorie()==null?null:q.getCategorie().getNom()).reponses(q.getReponses().stream().map(a->ReponseDTO.builder().id(a.getId()).texte(a.getTexte()).correcte(a.getCorrecte()).option(a.getOption()).build()).toList()).dateCreation(q.getDateCreation()).build(); }
    private Enseignant currentTeacher(){ String email=SecurityContextHolder.getContext().getAuthentication().getName(); Utilisateur u=utilisateurRepository.findByEmail(email).orElseThrow(()->new ResourceNotFoundException("User not found")); if(!(u instanceof Enseignant t)) throw new ForbiddenException("Teacher account required"); return t; }
    private String text(Row r,int i){ Cell c=r.getCell(i,Row.MissingCellPolicy.RETURN_BLANK_AS_NULL); return c==null?"":new DataFormatter().formatCellValue(c).trim(); } private int number(Row r,int i,int fallback){ try{return Integer.parseInt(text(r,i));}catch(Exception e){return fallback;} } private <E extends Enum<E>> E parse(Class<E> type,String value,E fallback){ try{return value.isBlank()?fallback:Enum.valueOf(type,value.trim().toUpperCase());}catch(Exception e){throw new BusinessException("Invalid "+type.getSimpleName()+": "+value);} } private String blank(String v){return v==null||v.isBlank()?null:v.trim();}
}
